### ISSUE TITLE
Enable CORS - Cross Origin Resource Sharing

### ISSUE THREAD

**Issue by dayne** [gina-alaska/gina-ogc#5]
The use of GINA's tile end points currently are being limited by not having CORS enabled.

https://www.w3.org/wiki/CORS_Enabled

To enable this we need to add the following 

_nginx_

> `add_header Access-Control-Allow-Origin *;`

_apache_

> `Add Header set Access-Control-Allow-Origin "*"`

This feature request prompted by Cesium testing issues by Khan and from a GINA user support request from Jack Smodey at Alaska DNR.  Jack is hoping to see it enabled for use in the DNR Alaska Mapper web interface.

Need @teknofire and @spruceboy to review this and chime in.

**Comment by spruceboy** [comment]
I setup a proxy  though hippy that uses:
Header set Access-Control-Allow-Origin "*"
And that works for Khan's cesium examples. 
Can I get this added to fish and fowls apache config?  I would add it, but they are chef-ed, on the old chef server.

**Comment by teknofire** [comment]
You should be able to update https://github.com/gina-alaska/shiv-cookbook/blob/master/templates/default/tiles.conf.erb

with that config change and then we can push it up to those servers

**Comment by spruceboy** [comment]
It is there, I added it mid march.

**Comment by teknofire** [comment]
ah, yes

looks like chef-client hasn't been running because of errors with the cookbook trying to use the deprecated yum-epel cookbook, looking into getting it working again.

**Comment by teknofire** [comment]
Ok, the cookbook has been update and deployed to the servers.
